# Generated by Django 6.0.7 on 2026-07-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка на проект'),
        ),
    ]
