# Generated by Django 6.0.7 on 2026-09-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(choices=[('higher', 'Высшее образование'), ('additional', 'Дополнительное образование')], max_length=20, verbose_name='Тип образования')),
                ('specialty', models.CharField(max_length=255, verbose_name='Специальность')),
                ('degree', models.CharField(max_length=100, verbose_name='Степень')),
                ('start_year', models.PositiveIntegerField(verbose_name='Год начала')),
                ('end_year', models.PositiveIntegerField(verbose_name='Год окончания')),
                ('institution', models.CharField(max_length=255, verbose_name='Учебное заведение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('document_url', models.URLField(blank=True, verbose_name='Ссылка на документ')),
            ],
            options={
                'verbose_name': 'образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['start_year'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('start_year', models.PositiveIntegerField(verbose_name='Год начала')),
                ('end_year', models.PositiveIntegerField(verbose_name='Год окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опыт',
                'verbose_name_plural': 'Опыта',
                'ordering': ['start_year'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория навыков',
                'verbose_name_plural': 'Категории навыков',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.skillcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
