# Generated by Django 6.0.7 on 2026-09-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['start_year'], 'verbose_name': 'Образование', 'verbose_name_plural': 'Образование'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['start_year'], 'verbose_name': 'Опыт', 'verbose_name_plural': 'Опыт'},
        ),
    ]
